# Generated by Django 3.0.5 on 2024-01-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20240110_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
